import { Form, Head, router } from '@inertiajs/react';
import { Pencil, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import InputError from '@/components/input-error';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';
import jobs from '@/routes/jobs';

/*
|--------------------------------------------------------------------------
| [EXAM] PSRS Part 2.I - Job Listings Management (list + add + edit + delete)
|--------------------------------------------------------------------------
| [REUSE] Every single import above already existed in your project:
|           Form, Head, router      -> @inertiajs/react
|           InputError              -> used by resources/js/pages/auth/login.tsx
|           Button/Input/Label      -> the shadcn components in components/ui
|           Spinner                 -> components/ui/spinner.tsx (login uses it)
|           Badge                   -> components/ui/badge.tsx
|           jobs                    -> GENERATED by Wayfinder from routes/web.php
|         You are writing glue, not components.
*/

// [LEARN] Describe the server's data as a TypeScript type. Now if you rename a
//         column in the migration and forget to update React, the editor tells
//         you immediately instead of the page rendering "undefined".
type Job = {
    id: number;
    title: string;
    department: string;
    location: string;
    salary: string;
    is_active: boolean;
    applications_count: number;
};

/*
  [LEARN] THE PAGINATOR SHAPE. Once the controller calls ->paginate() instead of
          ->get(), the prop is no longer an array - it is an object whose rows
          live under `data`, plus the counters Laravel adds. Getting a blank
          table right after adding pagination is almost always because the page
          is still mapping over `jobs` instead of `jobs.data`.
*/
type Paginated<T> = {
    data: T[];
    current_page: number;
    last_page: number;
    from: number | null;
    to: number | null;
    total: number;
    prev_page_url: string | null;
    next_page_url: string | null;
};

type Props = {
    jobs: Paginated<Job>;
    filters: { search: string };
    canManage: boolean; // sent by JobController@index - the server decides, not React
};

// [EXAM] PSRS 2.III - these three options exist so your demo can hit every
//        branch of the scoring rule without typos. Remote=+3, DAR=+2, other=+1.
const LOCATIONS = ['Remote', 'DAR ES SALAAM', 'Mwanza', 'Dodoma', 'Arusha'];

export default function Index({ jobs: page, filters, canManage }: Props) {
    const list = page.data;

    // [LEARN] The search box IS controlled (useState), unlike the job form.
    //         A filter is not a form submission - we want to read its value in
    //         an event handler, so React needs to own it.
    const [search, setSearch] = useState(filters.search ?? '');

    /*
      [LEARN] router.get() re-requests the SAME page with new query params.
                preserveState: keeps your scroll position and open form
                replace:       does not add a history entry per keystroke,
                               so Back does not walk through every search
    */
    const runSearch = (value: string) => {
        router.get(
            jobs.index.url(),
            value ? { search: value } : {},
            { preserveState: true, replace: true, preserveScroll: true },
        );
    };
    // [LEARN] ONE piece of state runs the whole inline form:
    //           null      -> form hidden
    //           'new'     -> form open, creating
    //           a Job     -> form open, editing that job
    //         This is why we never needed jobs/create.tsx or jobs/edit.tsx.
    const [editing, setEditing] = useState<Job | 'new' | null>(null);
    const isEditing = editing !== null && editing !== 'new';

    const money = (value: string) =>
        'Tsh. ' + new Intl.NumberFormat('en-TZ').format(Number(value));

    return (
        <>
            <Head title="Job Listings" />

            <div className="flex h-full flex-1 flex-col gap-6 overflow-x-auto rounded-xl p-4">
                <div className="flex items-center justify-between gap-4">
                    <div>
                        <h1 className="text-2xl font-semibold">Job Listings</h1>
                        <p className="text-sm text-muted-foreground">
                            {page.total} posting{page.total === 1 ? '' : 's'}
                            {filters.search && ` matching "${filters.search}"`}
                        </p>
                    </div>

                    {/* [EXAM] PSRS 1.c - a viewer never even sees this button.
                        The route is ALSO guarded server-side; hiding a button is
                        convenience, never security. */}
                    {canManage && (
                        <Button
                            onClick={() => setEditing(editing ? null : 'new')}
                            variant={editing ? 'outline' : 'default'}
                        >
                            {editing ? <X /> : <Plus />}
                            {editing ? 'Cancel' : 'Add a job'}
                        </Button>
                    )}
                </div>

                {/* ---------------- INLINE CREATE / EDIT FORM ---------------- */}
                {canManage && editing && (
                    <div className="rounded-xl border p-4">
                        <h2 className="mb-4 font-medium">
                            {isEditing ? `Edit "${editing.title}"` : 'New job posting'}
                        </h2>

                        {/*
                          [REUSE] THIS IS THE LOGIN FORM PATTERN, copied verbatim from
                                  resources/js/pages/auth/login.tsx. Open them side by side.

                          [LEARN] <Form> submits the real DOM form, so inputs need only a
                                  `name`. No useState per field, no onChange, no manual
                                  post(). Because it is UNCONTROLLED you use defaultValue,
                                  never value.

                          [LEARN] ***THE key PROP IS NOT OPTIONAL HERE.*** Uncontrolled
                                  inputs only read defaultValue when they first mount. Click
                                  "Edit" on a second job and React would reuse the same DOM
                                  nodes, leaving the FIRST job's text on screen. Changing the
                                  key forces a fresh mount. This bug looks like your backend
                                  is broken; it is not.

                          [LEARN] jobs.store.form() - note `.form` is a property of the
                                  helper, called with the route params. It is NOT
                                  jobs.store().form(). For PUT, Wayfinder adds ?_method=PUT
                                  because browsers can only really send GET and POST.
                        */}
                        <Form
                            key={isEditing ? editing.id : 'new'}
                            {...(isEditing
                                ? jobs.update.form.put(editing.id)
                                : jobs.store.form())}
                            resetOnSuccess
                            onSuccess={() => setEditing(null)}
                            className="grid gap-4 sm:grid-cols-2"
                        >
                            {({ processing, errors }) => (
                                <>
                                    <div className="grid gap-2">
                                        <Label htmlFor="title">Title</Label>
                                        <Input
                                            id="title"
                                            name="title"
                                            required
                                            autoFocus
                                            placeholder="Software Engineer"
                                            defaultValue={isEditing ? editing.title : ''}
                                        />
                                        <InputError message={errors.title} />
                                    </div>

                                    <div className="grid gap-2">
                                        <Label htmlFor="department">Department</Label>
                                        <Input
                                            id="department"
                                            name="department"
                                            required
                                            placeholder="ICT"
                                            defaultValue={isEditing ? editing.department : ''}
                                        />
                                        <InputError message={errors.department} />
                                    </div>

                                    <div className="grid gap-2">
                                        <Label htmlFor="location">Location</Label>
                                        {/*
                                          [LEARN] A PLAIN <select>, not the shadcn <Select>.
                                                  The shadcn one is a Radix widget that needs
                                                  extra wiring to submit inside a real form.
                                                  Under exam pressure, native beats pretty.
                                        */}
                                        <select
                                            id="location"
                                            name="location"
                                            required
                                            defaultValue={isEditing ? editing.location : 'Remote'}
                                            className="h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs focus-visible:ring-[3px] focus-visible:outline-none"
                                        >
                                            {LOCATIONS.map((location) => (
                                                <option key={location} value={location}>
                                                    {location}
                                                </option>
                                            ))}
                                        </select>
                                        <InputError message={errors.location} />
                                    </div>

                                    <div className="grid gap-2">
                                        <Label htmlFor="salary">Monthly salary (Tsh)</Label>
                                        <Input
                                            id="salary"
                                            name="salary"
                                            type="number"
                                            required
                                            min={0}
                                            placeholder="1200000"
                                            defaultValue={isEditing ? editing.salary : ''}
                                        />
                                        <InputError message={errors.salary} />
                                    </div>

                                    <div className="sm:col-span-2">
                                        {/* [REUSE] Spinner-while-processing, exactly as the
                                            login button does it. */}
                                        <Button type="submit" disabled={processing}>
                                            {processing && <Spinner />}
                                            {isEditing ? 'Save changes' : 'Post job'}
                                        </Button>
                                    </div>
                                </>
                            )}
                        </Form>
                    </div>
                )}

                {/* ---------------- SEARCH ---------------- */}
                <form
                    className="flex gap-2"
                    onSubmit={(event) => {
                        event.preventDefault();
                        runSearch(search);
                    }}
                >
                    <Input
                        type="search"
                        value={search}
                        onChange={(event) => setSearch(event.target.value)}
                        placeholder="Search title, department or location..."
                        className="max-w-sm"
                    />
                    <Button type="submit" variant="outline">
                        Search
                    </Button>
                    {filters.search && (
                        <Button
                            type="button"
                            variant="ghost"
                            onClick={() => {
                                setSearch('');
                                runSearch('');
                            }}
                        >
                            Clear
                        </Button>
                    )}
                </form>

                {/* ---------------- THE LISTING ---------------- */}
                <div className="overflow-x-auto rounded-xl border">
                    <table className="w-full text-sm">
                        <thead className="bg-muted/50 text-left text-muted-foreground">
                            <tr>
                                <th className="p-3 font-medium">Title</th>
                                <th className="p-3 font-medium">Department</th>
                                <th className="p-3 font-medium">Location</th>
                                <th className="p-3 font-medium">Salary</th>
                                <th className="p-3 font-medium">Applicants</th>
                                <th className="p-3" />
                            </tr>
                        </thead>
                        <tbody>
                            {list.map((job) => (
                                <tr key={job.id} className="border-t">
                                    <td className="p-3 font-medium">
                                        {job.title}
                                        {!job.is_active && (
                                            <Badge variant="secondary" className="ml-2">
                                                closed
                                            </Badge>
                                        )}
                                    </td>
                                    <td className="p-3">{job.department}</td>
                                    <td className="p-3">
                                        {/* A visual hint of the priority this location earns. */}
                                        <Badge variant="outline">{job.location}</Badge>
                                    </td>
                                    <td className="p-3 tabular-nums">{money(job.salary)}</td>
                                    <td className="p-3 tabular-nums">{job.applications_count}</td>
                                    <td className="p-3">
                                        <div className="flex justify-end gap-2">
                                            {/* [LEARN] router.visit / .delete are the
                                                imperative version of <Link>. Use them from
                                                event handlers. */}
                                            <Button
                                                size="sm"
                                                variant="outline"
                                                onClick={() => router.visit(jobs.show(job.id))}
                                            >
                                                View &amp; apply
                                            </Button>

                                            {canManage && (
                                                <>
                                                    <Button
                                                        size="sm"
                                                        variant="outline"
                                                        onClick={() => setEditing(job)}
                                                    >
                                                        <Pencil />
                                                    </Button>
                                                    <Button
                                                        size="sm"
                                                        variant="destructive"
                                                        onClick={() =>
                                                            router.delete(jobs.destroy(job.id))
                                                        }
                                                    >
                                                        <Trash2 />
                                                    </Button>
                                                </>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}

                            {list.length === 0 && (
                                <tr>
                                    <td colSpan={6} className="p-6 text-center text-muted-foreground">
                                        {filters.search
                                            ? `No jobs match "${filters.search}".`
                                            : 'No jobs posted yet.'}
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>

                {/* ---------------- PAGINATION ---------------- */}
                {/*
                  [LEARN] Laravel's paginator also ships a `links` array, but its
                          labels are raw HTML entities ("&laquo; Previous"), which
                          React escapes - you would see the literal text unless you
                          used dangerouslySetInnerHTML. Building Prev / Next from
                          prev_page_url and next_page_url avoids that entirely and
                          is less code. Prefer it.
                */}
                {page.last_page > 1 && (
                    <div className="flex items-center justify-between gap-4">
                        <p className="text-sm text-muted-foreground tabular-nums">
                            Showing {page.from}–{page.to} of {page.total}
                        </p>

                        <div className="flex items-center gap-2">
                            <Button
                                size="sm"
                                variant="outline"
                                disabled={!page.prev_page_url}
                                onClick={() =>
                                    page.prev_page_url &&
                                    router.visit(page.prev_page_url, {
                                        preserveScroll: true,
                                    })
                                }
                            >
                                Previous
                            </Button>

                            <span className="text-sm tabular-nums">
                                Page {page.current_page} of {page.last_page}
                            </span>

                            <Button
                                size="sm"
                                variant="outline"
                                disabled={!page.next_page_url}
                                onClick={() =>
                                    page.next_page_url &&
                                    router.visit(page.next_page_url, {
                                        preserveScroll: true,
                                    })
                                }
                            >
                                Next
                            </Button>
                        </div>
                    </div>
                )}
            </div>
        </>
    );
}

/*
  [REUSE] The layout assignment pattern from your own pages/employees/index.tsx.
  [LEARN] resources/js/app.tsx picks the layout by page name (see its `layout`
          switch). This object is passed to that layout as PROPS - which is why
          the auth pages set { title, description } and app pages set
          { breadcrumbs }. Same mechanism, different layout.
*/
Index.layout = {
    breadcrumbs: [{ title: 'Jobs', href: jobs.index() }],
};
