<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreJobRequest;
use App\Models\Job;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Inertia\Inertia;

/**
 * [EXAM] PSRS Part 2.I - Job Listings Management.
 *
 * [REUSE] Exactly the shape of your app/Http/Controllers/VacancyController.php
 *         (generated by `php artisan make:controller X --resource`), with the
 *         empty method bodies filled in.
 *
 * [LEARN] THE SEVEN RESOURCE METHODS AND THEIR URLS. Memorise this table -
 *         one line in routes/web.php gives you all of it:
 *
 *           index()   GET     /jobs            jobs.index
 *           create()  GET     /jobs/create     jobs.create    <- we skip this
 *           store()   POST    /jobs            jobs.store
 *           show()    GET     /jobs/{job}      jobs.show
 *           edit()    GET     /jobs/{job}/edit jobs.edit      <- we skip this
 *           update()  PUT     /jobs/{job}      jobs.update
 *           destroy() DELETE  /jobs/{job}      jobs.destroy
 *
 *         We skip create() and edit() on purpose: our create/edit form lives
 *         INLINE on the index page (see resources/js/pages/jobs/index.tsx).
 *         Two fewer pages, two fewer round trips, ~8 minutes saved.
 */
class JobController extends Controller
{
    /**
     * [EXAM] PSRS 2.I - "View all active job postings."
     */
    public function index(Request $request)
    {
        $search = $request->string('search')->trim()->toString();

        $jobs = Job::query()
            // [LEARN] withCount('applications') adds an `applications_count`
            //         property using ONE extra SQL sub-query. The naive way -
            //         looping and calling $job->applications->count() - fires
            //         one query per row. That is the N+1 problem, and it is the
            //         most common performance question in a code review.
            ->withCount('applications')

            /*
            | [LEARN] when() applies the closure ONLY if the first argument is
            |         truthy. It saves you writing an if statement around the
            |         query and keeps the whole thing one fluent chain.
            |
            | [LEARN] ***WHY THE NESTED CLOSURE INSIDE?***
            |         Without it the orWhere clauses "leak" and OR themselves
            |         against every other condition in the query. SQL would read
            |
            |             WHERE is_active = 1 AND title LIKE ? OR department LIKE ?
            |
            |         which quietly returns inactive jobs. The inner closure
            |         wraps them in brackets:
            |
            |             WHERE is_active = 1 AND (title LIKE ? OR department LIKE ?)
            |
            |         This is one of the most common silent bugs in Laravel.
            */
            ->when($search, function ($query, $search) {
                $query->where(function ($grouped) use ($search) {
                    $grouped->where('title', 'like', "%{$search}%")
                        ->orWhere('department', 'like', "%{$search}%")
                        ->orWhere('location', 'like', "%{$search}%");
                });
            })

            ->latest()

            /*
            | [LEARN] paginate() replaces get(). It runs a COUNT query plus a
            |         LIMIT/OFFSET query, and returns a paginator that serialises
            |         to JSON as { data: [...], links: [...], total, ... }.
            |         So in React the rows are jobs.data, not jobs.
            |
            | [LEARN] ***withQueryString() IS THE LINE EVERYONE FORGETS.***
            |         Without it, clicking "page 2" produces /jobs?page=2 and
            |         DROPS ?search=engineer - so page 2 shows unfiltered
            |         results. With it, every page link keeps the current filters.
            */
            ->paginate(5)
            ->withQueryString();

        return Inertia::render('jobs/index', [
            'jobs' => $jobs,

            // Send the current search back so the input stays filled in after
            // the page reloads.
            'filters' => ['search' => $search],

            // [LEARN] Send PERMISSIONS to the frontend, do not re-implement the
            //         rules in React. The server stays the single source of
            //         truth; React just hides buttons it was told to hide.
            'canManage' => $request->user()->canManageJobs(),
        ]);
    }

    /**
     * [EXAM] PSRS 2.I - "Add jobs with details such as title, department,
     *        location and salary."
     *
     * [LEARN] Note the type hint: StoreJobRequest, not Request. Validation and
     *         authorisation already happened before this line runs. If you are
     *         inside this method, the data is guaranteed valid.
     */
    public function store(StoreJobRequest $request)
    {
        Job::create($request->validated());

        // [LEARN] to_route() = redirect()->route(). After a POST you ALWAYS
        //         redirect - this is the Post/Redirect/Get pattern. It stops
        //         the browser re-submitting the form when the user hits reload.
        //
        // [LEARN] ->with('success', ...) puts a one-request-only "flash"
        //         message in the session. Your starter kit already forwards
        //         flash data to React - look at the `share()` method in
        //         app/Http/Middleware/HandleInertiaRequests.php.
        return to_route('jobs.index')->with('success', 'Job posted.');
    }

    /**
     * [EXAM] PSRS 2.II - the page a candidate applies from.
     *
     * [LEARN] ROUTE MODEL BINDING. The parameter is typed `Job $job` and the
     *         route is /jobs/{job}. Laravel sees the match, runs
     *         Job::findOrFail($id) for you, and 404s automatically if it does
     *         not exist. You never write a lookup or an if-not-found check.
     */
    public function show(Request $request, Job $job)
    {
        return Inertia::render('jobs/show', [
            'job' => $job,

            // Has this signed-in user already applied? Drives the UI so we can
            // show "You have applied" instead of a form that will only fail.
            'alreadyApplied' => $job->applications()
                ->where('candidate_email', $request->user()->email)
                ->exists(),
        ]);
    }

    /**
     * [LEARN] We reuse StoreJobRequest here rather than generating an
     *         UpdateJobRequest, because the rules are identical. One less file
     *         to write and one less place for the two to drift apart.
     */
    public function update(StoreJobRequest $request, Job $job)
    {
        $job->update($request->validated());

        return to_route('jobs.index')->with('success', 'Job updated.');
    }

    public function destroy(Request $request, Job $job)
    {
        // [LEARN] THE POLICY CALL. Gate::authorize() runs JobPolicy::delete()
        //         and throws a 403 if it returns false. This is the record-level
        //         rule middleware cannot express: an editor may not delete a job
        //         that already has applicants, but an admin may.
        Gate::authorize('delete', $job);

        $job->delete();

        return to_route('jobs.index')->with('success', 'Job removed.');
    }

    /* ====================================================================
     | API - same data, JSON, guarded by the API key. routes/api.php
     ==================================================================== */

    /**
     * [EXAM] PSRS Part 1.e - the endpoint exposed to third-party services.
     *
     * [LEARN] The ONLY difference from index() is the response type:
     *         Inertia::render() for a browser, response()->json() for a
     *         machine. Same model, same scope, no duplicated business logic.
     */
    public function apiIndex()
    {
        return response()->json([
            'data' => Job::active()->get(),
        ]);
    }
}
